[package]
name = "plux-wasm-manager"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.plux]
git = "https://github.com/BleynChannel/plux-rs.git"
branch = "master"